### ISSUE TITLE
PhantomJS 2.0 Landed

### ISSUE THREAD

**Issue by metaskills** [nathanboktae/mocha-phantomjs#175]
Just gonna drop this here:

https://github.com/ariya/phantomjs/wiki/PhantomJS-2

**Comment by darrrk** [comment]
I try to replace phantomjs binary from 1.x to 2.x
And mocha-phantomjs not working with it now.
Cli process simply freezes on infinite time.

**Comment by nathanboktae** [comment]
I downloaded the mac OS X binary and it would just die.

Yes they [expliclity removed coffeescript](http://phantomjs.org/release-2.0.html) so it won't work at all as is. We either need to just use JavaScript or compile to JavaScript as part of a distribution - I prefer the former.

Some other things to consider for a major release:

- #164
- Split out the phantomjs core and the console parts #127

**Comment by metaskills** [comment]
> OS X binary and it would just die

Same here.

>  just use JavaScript 

That's cool with me.

**Comment by metaskills** [comment]
FYI, known issue for Mac download. I found this on their issues and am downloading it now.

https://github.com/eugene1g/phantomjs/releases

**Comment by nathanboktae** [comment]
Yup I got that too and ran our tests and found a bug and filed it already - ariya/phantomjs#12973. Could be some more too as there were about 5-7 failing tests. 2.1 is already being prepared.

**Comment by nathanboktae** [comment]
I want to talk more about splitting out the console and core parts here. For end users it doesn't matter, but it matters a lot for integrators, namely build plugin authors. Pinging all the ones I could find:

- Grunt plugin: @jdcataldo
- Gulp plugin: @mrhooray
- ghoul: @davidglivar
- mocha-phantomjs-istanbul (really a hooks module, but input is nice): @willembult

Integrators: would you be interested in moving over to a `mocha-phantomjs-core` module? this would save you a process fork, but also, we could revisit how the dependency to phantomjs is managed - I would imagine this core module to not declare it's dependency to phantomjs in npm (it's not a Node.js module, it's phantomjs, but there's no `ppm` or phantomjs package manager, so we piggyback on npm). So modules that depend on the core get to decide how it finds phantomjs - direct dependecy, peer, maybe consumed from some external config, whatever. I would imagine the CLI module, `mocha-phantomjs` to have a direct dependency on phantomjs (peer dependencies are a pain).

Thoughts?

**Comment by bithavoc** [comment]
:+1:

**Comment by mrhooray** [comment]
thanks @nathanboktae for taking the initiative

agree that cli/ghoul and grunt/gulp plugins are just different interfaces/frontends of core library. for example the gulp plugin only depends on `lib/mocha-phantomjs.coffee`

using phantomjs as peer dependency seems to be a reasonable compromise of many cases/concerns

**Comment by hatched** [comment]
Is there a timeline or task list for mocha-phantomjs to support phantomjs 2.0?

**Comment by jokeyrhyme** [comment]
Would it be possible for this core to support driving multiple versions of PhantomJS?

I actually find it useful that PhantomJS 1.9 is missing a few web platform APIs, so it would be terrific if I could run tests against both PhantomJS 1.9 and 2.x (and 3.x, etc).

**Comment by rjharmon** [comment]
I found that by transpiling the .coffee script to JS, and adjusting the launcher to use it, PhantomJS 2 runs the tests just fine.  1.9 also works fine with that change.  I'd suggest adjusting the build to use this technique short-term to fix the compatibility problem.

**Comment by nathanboktae** [comment]
Well a) we have no build as `mocha-phantomjs.coffee` is directly consumed b) we have supported `phantomjs lib/phantomjs ...` style execution that will break. Its a good time to do a major version to planning and executing that well is important.

**Comment by rjharmon** [comment]
That sounds fine - I'm a fan of good planning too.  Meanwhile, it's borked :( ...  Any way to include a .js version and probe `phantomjs -v` from the launcher?  I know it's just a band-aid, but it's a band-aid with a purpose: not to replace planning for major version-bump, just to enable compatibility in short-term. 

PJS2 users can always choose to use the .js version if they want direct `phantomjs lib/phantomjs ...` style. Their alternative to having a centrally-provided band-aid, is to hack their installation the way I described (which is its own type of bandaid, I admit).  

Your call.

**Comment by nathanboktae** [comment]
> Meanwhile, it's borked :(

What is? From your previous comment, sounds like you're fine.

> I found that by transpiling the .coffee script to JS, and adjusting the launcher to use it, PhantomJS 2 runs my test suite without difficulty.

I had done this too, but a lot of tests were failing.

**Comment by nathanboktae** [comment]
I'd also like to remove the `mochaPhantomJS` global. I think we can listen on on [`onResourceRecieved` event](https://github.com/ariya/phantomjs/wiki/API-Reference-WebPage#webpage-onResourceReceived) and monkey-patch mocha, removing the need for everyone to remember to do:

 ```javascript
if (window.mochaPhantomJS) {
  mochaPhantomJS.run()
} else {
  mocha.run()
}
```

**Comment by SirZach** [comment]
subscribing. i need phantomjs v2 for the performance api

**Comment by nathanboktae** [comment]
I started work on this in the [v4 branch](https://github.com/metaskills/mocha-phantomjs/tree/v4). It's not pointing at phantomjs2 yet.

**Comment by mislav** [comment]
For my purposes, I've created a shim executable for `phantomjs` that detects if CoffeeScript files are being passed, and transparently compiles them to JS before they reach actual PhantomJS:

```sh
#!/bin/bash
set -e
phantomjs="$(which phantomjs)"

coffee-convert() {
  local file="${1?}"
  local dest="${file%.coffee}.js"
  [ "$dest" -nt "$file" ] || coffee -c "$file"
  echo "$dest"
}

if [[ $("$phantomjs" -v) != 1.* ]]; then
  args=()
  for arg; do
    if [[ $arg == *.coffee ]]; then
      arg="$(coffee-convert "$arg")"
    fi
    args[${#args[@]}]="$arg"
  done
  set -- "${args[@]}"
fi

exec "$phantomjs" "$@"
```

Use it like:

```
$ mocha-phantomjs --path ./my/phantomjs-shim
```

**Comment by nathanboktae** [comment]
Awesome that'll be great for people migrating or people wanting to keep writing tests in CoffeeScript.

**Comment by nathanboktae** [comment]
I have published `4.0.0-beta1` out now that uses `mocha-phantomjs-core` and `phantomjs2`. The biggest blocker is there are no official linux packages out for phantomjs2, so install fails on linux. If any linux users want to test this, I'd either use `mocha-phantomjs-core` directly or install it ignoring errors, if possible, then use the `-p` option to point it at your binary or have it in your path.

I need to update the readme in the `v4` branch, but the breaking changes off the top of my head:
- uses `mocha-phantomjs-core` now so `mocha-phantomjs.coffee` is totally gone. build plugin users should use that package directly and avoid an unnessecary process invocation, and have full control over what phantomjs they use and the options going into it.
- `mochaPhantomJS` global is gone. Environment variables are on `mocha.env` and simply calling `mocha.run()` works since `mocha-phantomjs-core` is now monkey-patching mocha when it's loaded. This also simplifies the loading detection logic.
- Errors now go to `stderr` not `stdout`.

Issues:
- cookie tests are failing due to changes in phantomjs 2 - see nathanboktae/mocha-phantomjs-core#4
- loading an invalid reporter hangs phantomjs due to ariya/phantomjs#12973

**Comment by mislav** [comment]
> I have published 4.0.0-beta1 out now that uses mocha-phantomjs-core

So what functionality does this project now add on top of `mocha-phantomjs-core`?

**Comment by nathanboktae** [comment]
The CLI. `mocha-phantomjs-core` is just phantomjs code. In fact I could make python and Ruby packages out of it for those developers, as there is no node.js code there.

**Comment by nathanboktae** [comment]
I unplublished `4.0.0-beta1` due to issues with `phantomjs2` not working, which is a bad fork of `phantomjs` which properly has not gone to phantomjs 2 yet because there are no official binaries. (see Medium/phantomjs#288 and #192).

Anyone who was using 4.0.0-beta1 can use the git tag `4.0.0-beta1` or branch `v4` (recommended). If you really want phantoms2, you can use that and put phantomjs in your path, use the `-p` flag, or use `mocha-phantomjs-core` and call phantomjs directly however you wish.

**Comment by jonnor** [comment]
Seems v4 has been merged to master now

**Comment by nathanboktae** [comment]
Yes, `4.0.0` is out but it is not on `phantomjs2` so I didn't close this. After 9 months there's still resolution for the various linux distro binaries, and the npm bug where it does a phantomjs peerDependency of `^1.9.7-15` even though it specifies `1.9.1-1.9.7-15` was getting to be way to painful.

**Comment by mwoc** [comment]
https://github.com/Medium/phantomjs/issues/288
Phantomjs 2.1 is now live, so hopefully soon offered by the phantomjs npm package too

**Comment by nathanboktae** [comment]
Oh that's nice.

I am actually planning on moving away from depending on the npm package `phantomjs` due to issues like these, and I am working on support for slimerjs now and [it's basically working](https://travis-ci.org/nathanboktae/mocha-phantomjs-core/builds/104250465). I want to switch to a BYOB Bring-your-own-binary style full on that `mocha-phantomjs-core` uses (You have been able to use phantomjs 2.0 with [mocha-phantomjs-core](https://github.com/nathanboktae/mocha-phantomjs-core) for months now).

**Comment by mmwtsn** [comment]
PhantomJS [v2.1.7](https://github.com/Medium/phantomjs/releases/tag/v2.1.7) is out now. Any updates here?

**Comment by jdcataldo** [comment]
Support was added in v3.0 https://github.com/jdcataldo/grunt-mocha-phantomjs/commit/63b7ff33e3c7d0df423877ce9a9996403c3bde5e

**Comment by Pomax** [comment]
just ran into the `SyntaxError: Parse error` error (no information on what goes wrong, running in the browser shows zero console errors), is mocha-phantomjs ever updating to 2.x? Especially after a year and a half of "maybe"? =)

**Comment by karlbright** [comment]
Hi Mike, most likely no. This project was more an experiment in how it
could work together. Nowadays testing like this is handled by other
libraries in a much cleaner way. Karma is a good example of this and will
run mocha tests with phantomjs, and other browsers, with just some simple
configuration.

**Comment by nathanboktae** [comment]
>  This project was more an experiment in how it
could work together.

Don't speak on behalfof this project if your not a contributor, because that is not true at all.

`mocha-phantomjs-core` has been supporting phantomjs 2 for a year now and sliders as of recently. The gulp and grunt plugins got switched over too.

Long term plans are to incorporate the client functionality into core which will then eclipse this project.

`mocha-phantomjs` is simpler to setup than karma and gives you full control over the test runner HTML. But if you want to test other browsers beyond Firefox and phantomjs, go with Karma.

**Comment by karlbright** [comment]
Complete apologies. I had a similar repo with the same name at one point
and got completely confused while looking at this from my phone. Sorry
about that @nathanboktae. That's completely my bad.

**Comment by nathanboktae** [comment]
Ah ok thanks for the explanation

**Comment by Pomax** [comment]
@nathanboktae does that mean this issue doesn't need to stay open anymore?

As for my particular usecase, one of our files used ES6 syntax functions, i.e.:
```
...
  render() {
    ...
  },
...
```
but mocha-phantom was only able to state the SyntaxError, not in which file it found it, or the line of code that triggered it; If that's a fixable thing that's probably worth fixing.

**Comment by nathanboktae** [comment]
> If that's a fixable thing that's probably worth fixing.

It's not fixable. PhantomJS is based on QT3 for 1.x, and QT5 for 2.x and neither supports ES6. The JavaScriptCore, the [JavaScript runtime that phantomjs](https://ariya.io/2014/08/phantomjs-2-and-javascript-goodies) uses has to be upgraded.

**Comment by Pomax** [comment]
I'm using fixable loosely - seeing the line in question and the file it was signalled in is just as good of course. The problem I had was seeing the equivalent of "something went wrong" without any additional information, so if phantom generates more data (file+line number for instance) but mocha-phantom right now doesn't proxy that to the console, that would be quite valueable to fix

**Comment by omouse** [comment]
just noticed that phantomjs is deprecated and was renamed to phantomjs-prebuilt. annoying to update dependencies and I noticed it's still at 1.9.x in the package.json.

**Comment by jpgcode** [comment]
Hi, can someone give an update on this one? This module is still using phantomjs 1.9.x, It is hard to upgrade it to version 2?

**Comment by jpgcode** [comment]
Nevermind, just read the above comments, it works with `mocha-phantomjs-core`. Please update this ticket or mark this project as deprecated in favor of `mocha-phantomjs-core` if this project will not be longer maintained.

**Comment by nathanboktae** [comment]
Yeah I need to move the command line parsing over to `mocha-phantomjs-core` before I can tell everyone to switch over. Also you can use phantomjs2 with this by pointing to the phantomjs2 binary with the`-p` option.

**Comment by Pomax** [comment]
@nathanboktae  good idea to put that information prominently at the top of the README.md (probably in a short section after "Usage" titled "Using with Phantom 2.x" and then maybe even refer to that section already all the way at the start of the README.md doc?) rather than having it only as a comment in a closed issue. This information deserves some permanence, at least until the CLI parsing's been switched over.

**Comment by nathanboktae** [comment]
Good idea @Pomax I'll add it to the README.
