### ISSUE TITLE
Live web site with authentication

### ISSUE THREAD

**Issue by s-KaiNet** [nathanboktae/mocha-phantomjs#236]
Is it possible to run `mocha-phantomjs` on a site which requires authentication (for example form based auth, or windows)?

**Comment by nathanboktae** [comment]
I think you're misunderstanding what `mocha-phantomjs` does. it takes mocha tests that run in a browser on some site and pipes out the output. It's not running the tests from the outside, which is probably what you want. Try [`mocha-casperjs`](https://github.com/nathanboktae/mocha-casperjs) or Selenium for those cases.

Otherwise no, but you can specify query string parameters and cookies before you start, which might help you there.

**Comment by s-KaiNet** [comment]
May be I'm not good at explanation, sorry. Yes, I need to run tests in a browser on some site, but this site requires windows authentication.   
Thanks for your advice, will take a look into different options.
