### ISSUE TITLE
Update / Remove CHANGELOG

### ISSUE THREAD

**Issue by jonny-improbable** [nathanboktae/mocha-phantomjs#238]
Hi @nathanboktae, thanks for your contributions to this very useful library.

The `CHANGELOG` file appears to have not been updated since release 3.5 and there are no entries for the newer 4.x releases (I'm am currently trying to see what changes from 4.0 -> 4.1 may impact our project).

Thanks!

**Comment by nathanboktae** [comment]
Yeah I'm not sure if @metaskills had some totally automated process for it, but I should figure out one (it might not be in the same format), but here's `git log --oneline --decorate`:

cfd02ef (HEAD -> master, tag: v4.1.0, origin/master, origin/HEAD) Release 4.1.0
ebd42f1 Merge pull request #237 from francetv/master
424dd4a Put back original error codes
bce6960 Don't use process.exit, but set exit code
46cbb35 Merge pull request #232 from astorije/patch-2
599953b Use SVG version of the Travis CI badge
ba4b66c Merge pull request #229 from erikvold/package-desc-edit
b907296 Edit package.json nocha -> mocha
6d8d25c Shorten and simplify the reporter README section. Fixes #208.
ad77952 (tag: v4.0.2) Don't block usage of xunit with file since it has been fixed (mochajs/mocha #2005)
39996c1 Add a test for the phantomjs bug in 1.9.8 described in #167 and ariya/phantomjs #12697
22efbb6 (tag: v4.0.1) Version 4.0.1
a148039 Merge pull request #205 from kaelzhang/master
dcbaafe Uses `require.resolve` to get the realpath of mocha-phantomjs-core.js, fixes #204
9fed801 (tag: v4.0.0) Merge v4 into master
