### ISSUE TITLE
how to use Page Module inside tests

### ISSUE THREAD

**Issue by basherr** [nathanboktae/mocha-phantomjs#260]
There isn't such example using `webpage module` with `mocha`?

Test `test.js`
```
consolge.log(window.page);
ReferenceError: Can't find variable: page

   at file:///C:/tests/test.js:1
```

**Comment by nathanboktae** [comment]
No because you can't. `mocha-phantomjs` takes a mocha that's running in the browser and pipes the result out to your console - mocha and all your tests run in the browser, not knowing phantom is there (most likely). the page object is on the phantomjs automation side. `mocha-phantomjs` exposes a little bit of that.

What are you trying to do? if you're trying to do more end-to-end or integration tests, look at `mocha-casperjs` or honestly these days Nightmare.js is the best, as phantomjs is basically dead.

**Comment by basherr** [comment]
I would like write integration tests with `nightmare/phantomjs`  with `Mocha`. Is it possible to load these integration tests within browser with any of them?
