### ISSUE TITLE
update mocha-phantomjs-core

### ISSUE THREAD

**Issue by DanielRuf** [nathanboktae/mocha-phantomjs#261]
mocha-phantomjs-core is still pinned to 1.x

**Comment by nathanboktae** [comment]
Please do a search before filing issues. #259, #167, #224, #245, and about 6 others talk about this.

**Comment by DanielRuf** [comment]
Related: https://github.com/jquery/jquery/issues/3955

**Comment by nathanboktae** [comment]
Do you mean to update `mocha-phantomjs-core` or `phantomjs` ? 

In general I would recommend [mocha-chrome](https://github.com/shellscape/mocha-chrome) these days instead of using `phantomjs`. If you still like phantomjs, you can use `mocha-phantomjs-core` directly with phantomjs 2.

**Comment by DanielRuf** [comment]
Right but what about existing projects? It is definitely helpful to have a new release with a newer `mocha-phantomjs-core` version. Or isn't this here actively maintained anymore?

**Comment by nathanboktae** [comment]
No it's useful to update the `mocha-phantomjs-core` version. I need to see if I need to take a major version change for that upgrade though. However your issue in the linked project is due to `phantomjs`, and honestly even with phantomjs 2.x you'll still run into another wonky phantomjs issue later. Running Chrome & Firefox fully headless in an uatomated fashion and then using the regular windowed mode for debugging is the dream we've all been waiting for and it's here. Phantomjs was a stopgap to this. Even phantomjs [itself is not actively maintained anymore](https://www.infoq.com/news/2017/04/Phantomjs-future-uncertain).
