### ISSUE TITLE
OSX Garbled output chars

### ISSUE THREAD

**Issue by topherbullock** [nathanboktae/mocha-phantomjs#60]
Instead of the snazzy checkmarks and X'es I get garbled characters. 

â—¦ is a test that passes: 
âœ“ is a test that passes 
â—¦ is a test that fails: 
1) is a test that fails

![screen shot 2013-04-29 at 6 42 05 pm](https://f.cloud.github.com/assets/1895900/441530/0bb9b540-b11e-11e2-9daa-a5f8379cc294.png)

could be something in my .bashrc.. but my terminal is set to UTF-8 and changing it to anything else just makes it worse.

**Comment by r4d1n** [comment]
It might be nice to make this more explicit in the docs. Just a little note alongside the example, maybe, since it took me a while (and a trip down a google rabbit hole thinking I had to do something to my terminal encoding) to find this issue and figure out why the characters weren't showing up properly.
