### ISSUE TITLE
Failed to start mocha: Init timeout

### ISSUE THREAD

**Issue by FoxGit** [nathanboktae/mocha-phantomjs#73]
I'd like to use this Plugin to generate reports of my unit tests. I am currently experiencing the following problem:

https://github.com/jdcataldo/grunt-mocha-phantomjs/issues/15

I use [grunt-mocha](https://github.com/kmiyashiro/grunt-mocha) which works just fine with my test index.html but lacks reporting capabilities. Do I miss something important by using this Plugin with the same test index.html file?

Thx in advance

**Comment by charlieWasp** [comment]
A year has passed, and I've got the same error :)

**Comment by nathanboktae** [comment]
This error means that `mochaPhantomJS.run()` was not called within a specified amount of time (IIRC 15secods). Since you control your test HTML, you'll need to make sure that it's being called correctly. It could be anything from a library that fails to run in phantom, to a simple bug, to just calling `mocha.run()` and not `mochaPhantomJS.run()` (btw, in 4.0 you won't need to do this).

**Comment by charlieWasp** [comment]
Oh, I see, now I use `mochaPhantomJS.run()` and all work right! Thank you! I read this tip, but totally forgot where to use it :smile:

**Comment by nathanboktae** [comment]
Good to hear :) and good to hear my work to remove that need will be an improvement - the goal of `mocha-phantomjs` is that it just builds on your vanilla testing work, and that was the one thing not conforming to that.
